# =================================
# SORTIE A DOUALA CONFIGURATION
# =================================
server.servlet.context-path=/hair-salon-app

# =================================
# DATABASE & MULTIPART CONFIG
# =================================

spring.datasource.url=jdbc:mysql://localhost:3306/hair_salon_db?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true


# SQL Encoding
spring.sql.init.encoding=UTF-8

# =================================
# CONFIGURE MAIL (Décommenter si nécessaire)
# =================================
 spring.mail.default-encoding=UTF-8
 spring.mail.host=smtp.mail.yahoo.com
 spring.mail.username=bjustinlorrain@yahoo.fr
 spring.mail.password=sfdxonhagkqrnpvv
 spring.mail.port=587
 spring.mail.protocol=smtp
 spring.mail.test-connection=false
 spring.mail.properties.mail.smtp.connectiontimeout=5000
 spring.mail.properties.mail.smtp.timeout=5000
 spring.mail.properties.mail.smtp.writetimeout=5000
 spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true

# =================================
# APPLICATION AUTH CONFIG
# =================================
app.auth.tokenSecret=HairSalon
app.auth.tokenExpirationMsec=86400000  
app.auth.refreshTokenExpirationMsec=604800000  
app.global_username_email=HairSalon

# =================================
# SPRING ACTUATOR CONFIG (Endpoints d'administration)
# =================================
management.endpoints.web.exposure.include=*
